import unittest

from scripts.context_regen_postprocess import (
    apply_deterministic_postprocessing,
    upsert_frontmatter_field,
)


TODAY = "2026-08-27"


class TestContextRegenPostprocess(unittest.TestCase):
    def test_unchanged_content_does_not_mutate_freshness_fields(self):
        source = """---
domain: infra
last_reviewed: 2026-08-01
---

# Context

## Freshness
- `last_reviewed`: 2026-08-01
"""

        out = apply_deterministic_postprocessing(
            source_md=source,
            generated_md=source,
            today_iso=TODAY,
        )

        self.assertNotIn("`generated_by`", out)
        self.assertIn("last_reviewed: 2026-08-01", out)
        self.assertIn("- `last_reviewed`: 2026-08-01", out)
        self.assertEqual(out, source.rstrip() + "\n")

    def test_changed_content_updates_frontmatter_and_freshness_once(self):
        source = """---
domain: infra
last_reviewed: 2026-08-01
---

# Context

## Freshness
- `last_reviewed`: 2026-08-01
- `generated_by`: manual
"""

        generated = source + "\nExtra line\n"

        out = apply_deterministic_postprocessing(
            source_md=source,
            generated_md=generated,
            today_iso=TODAY,
        )

        self.assertIn(f"last_reviewed: {TODAY}", out)
        self.assertIn(f"- `last_reviewed`: {TODAY}", out)
        self.assertIn("- `generated_by`: CI-generated", out)
        self.assertEqual(out.count("- `generated_by`"), 1)

    def test_generated_by_frontmatter_is_stamped_over_model_output(self):
        """A model-supplied `generated_by` is replaced, not trusted.

        The org context index enforces a closed vocabulary (manual / AI-assisted /
        CI-generated), and leaving this field to the model is how `generated_by: "OpenAI"`
        reached a committed file.
        """
        source = """---
domain: infra
generated_by: manual
last_reviewed: 2026-08-01
---

# Context

## Freshness
- `last_reviewed`: 2026-08-01
"""

        generated = source.replace("generated_by: manual", 'generated_by: "OpenAI"')

        out = apply_deterministic_postprocessing(
            source_md=source,
            generated_md=generated,
            today_iso=TODAY,
        )

        self.assertIn("generated_by: CI-generated", out)
        self.assertNotIn("OpenAI", out)
        self.assertEqual(out.count("generated_by:"), 1)

    def test_missing_freshness_section_is_added(self):
        source = """---
domain: infra
last_reviewed: 2026-08-01
---

# Context
"""

        generated = source + "\nChanged\n"

        out = apply_deterministic_postprocessing(
            source_md=source,
            generated_md=generated,
            today_iso=TODAY,
        )

        self.assertIn("## Freshness", out)
        self.assertIn(f"- `last_reviewed`: {TODAY}", out)
        self.assertIn("- `generated_by`: CI-generated", out)

    def test_template_style_bullets_are_updated_in_place(self):
        """`- **Last reviewed:**` is recognised, not shadowed by a second slug-style bullet.

        CONTEXT_TEMPLATE.md ships this style, so before it was recognised a template-shaped
        file grew a duplicate bullet on every run while the readable one stayed frozen.
        """
        source = """---
domain: infra
last_reviewed: 2026-08-01
---

# Context

## Freshness

- **Last reviewed:** 2026-08-01
- **Review confidence:** high
- **Generated by:** manual
- **Validated by:** Someone
"""

        generated = source + "\nChanged\n"

        out = apply_deterministic_postprocessing(
            source_md=source,
            generated_md=generated,
            today_iso=TODAY,
        )

        self.assertIn(f"- **Last reviewed:** {TODAY}", out)
        self.assertIn("- **Generated by:** CI-generated", out)
        self.assertNotIn("`last_reviewed`", out)
        self.assertNotIn("`generated_by`", out)
        self.assertEqual(out.count("Last reviewed"), 1)
        self.assertEqual(out.count("Generated by"), 1)
        self.assertIn("- **Validated by:** Someone", out)

    def test_a_committed_legacy_log_block_is_deleted(self):
        """A block an earlier revision of the regenerator appended is removed, not rewritten.

        Dropping it is also not a review: a file whose only difference is the vanished block
        keeps its `last_reviewed` date, so the migration does not stamp every consumer repo.
        """
        source = """---
domain: infra
last_reviewed: 2026-08-01
---

# Context

## Freshness

- **Last reviewed:** 2026-08-01

Recent changes (last 7 days of git log):
old entry
"""

        out = apply_deterministic_postprocessing(
            source_md=source,
            generated_md=source,
            today_iso=TODAY,
        )

        self.assertNotIn("Recent changes", out)
        self.assertNotIn("old entry", out)
        self.assertIn("last_reviewed: 2026-08-01", out)
        self.assertIn("- **Last reviewed:** 2026-08-01", out)
        self.assertNotIn(TODAY, out)
        self.assertTrue(out.rstrip().endswith("- **Last reviewed:** 2026-08-01"))

    def test_a_bullet_is_appended_below_the_last_bullet(self):
        """`## Freshness` is the final section, so the section body runs to EOF."""
        source = """---
domain: infra
last_reviewed: 2026-08-01
---

# Context

## Freshness

- **Last reviewed:** 2026-08-01
"""

        generated = source.replace("# Context", "# Context\n\nA substantive change.")

        out = apply_deterministic_postprocessing(
            source_md=source,
            generated_md=generated,
            today_iso=TODAY,
        )

        self.assertIn(f"- **Last reviewed:** {TODAY}", out)
        self.assertIn("- **Generated by:** CI-generated", out)
        self.assertGreater(out.index("Generated by"), out.index("Last reviewed"))

    def test_appended_bullet_follows_the_sections_existing_style(self):
        """A section written in one style does not end up carrying both."""
        prose_source = """---
domain: infra
---

## Freshness

- **Last reviewed:** 2026-08-01
"""
        slug_source = """---
domain: infra
---

## Freshness
- `last_reviewed`: 2026-08-01
"""

        for source, expected, unexpected in (
            (prose_source, "- **Generated by:** CI-generated", "`generated_by`"),
            (slug_source, "- `generated_by`: CI-generated", "**Generated by:**"),
        ):
            with self.subTest(source=expected):
                out = apply_deterministic_postprocessing(
                    source_md=source,
                    generated_md=source + "\nChanged\n",
                    today_iso=TODAY,
                )

                self.assertIn(expected, out)
                self.assertNotIn(unexpected, out)

    def test_upsert_frontmatter_field_sets_repo_deterministically(self):
        md = """---
repo: UNSET
owner: Cinfra
---

# Context
"""

        out = upsert_frontmatter_field(md, "repo", "guidion-digital/code-infrastructure")

        self.assertIn("repo: guidion-digital/code-infrastructure", out)
        self.assertNotIn("repo: UNSET", out)

    def test_transform_is_idempotent(self):
        source = """---
domain: infra
last_reviewed: 2026-08-01
---

# Context

## Freshness
- `last_reviewed`: 2026-08-01
"""
        generated = source + "\nChanged\n"

        once = apply_deterministic_postprocessing(
            source_md=source,
            generated_md=generated,
            today_iso=TODAY,
        )
        twice = apply_deterministic_postprocessing(
            source_md=once,
            generated_md=once,
            today_iso=TODAY,
        )

        self.assertEqual(once, twice)


if __name__ == "__main__":
    unittest.main()
