import unittest

from scripts.context_regen_postprocess import (
    apply_deterministic_postprocessing,
    strip_recent_changes,
    upsert_frontmatter_field,
)


TODAY = "2026-08-27"


class TestContextRegenPostprocess(unittest.TestCase):
    def test_unchanged_content_does_not_mutate_freshness_fields(self):
        source = """---
domain: infra
last_reviewed: 2026-08-01
---

# Context

## Freshness
- `last_reviewed`: 2026-08-01
"""

        out = apply_deterministic_postprocessing(
            source_md=source,
            generated_md=source,
            git_log="",
            today_iso=TODAY,
        )

        self.assertNotIn("`generated_by`", out)
        self.assertIn("last_reviewed: 2026-08-01", out)
        self.assertIn("- `last_reviewed`: 2026-08-01", out)
        # The log block is appended unconditionally, but that is not a reviewable change.
        self.assertEqual(strip_recent_changes(out), source.rstrip() + "\n")
        self.assertIn("Recent changes (last 7 days of git log):", out)

    def test_changed_content_updates_frontmatter_and_freshness_once(self):
        source = """---
domain: infra
last_reviewed: 2026-08-01
---

# Context

## Freshness
- `last_reviewed`: 2026-08-01
- `generated_by`: manual
"""

        generated = source + "\nExtra line\n"

        out = apply_deterministic_postprocessing(
            source_md=source,
            generated_md=generated,
            git_log="",
            today_iso=TODAY,
        )

        self.assertIn(f"last_reviewed: {TODAY}", out)
        self.assertIn(f"- `last_reviewed`: {TODAY}", out)
        self.assertIn("- `generated_by`: CI-generated", out)
        self.assertEqual(out.count("- `generated_by`"), 1)

    def test_generated_by_frontmatter_is_stamped_over_model_output(self):
        """A model-supplied `generated_by` is replaced, not trusted.

        The org context index enforces a closed vocabulary (manual / AI-assisted /
        CI-generated), and leaving this field to the model is how `generated_by: "OpenAI"`
        reached a committed file.
        """
        source = """---
domain: infra
generated_by: manual
last_reviewed: 2026-08-01
---

# Context

## Freshness
- `last_reviewed`: 2026-08-01
"""

        generated = source.replace("generated_by: manual", 'generated_by: "OpenAI"')

        out = apply_deterministic_postprocessing(
            source_md=source,
            generated_md=generated,
            git_log="",
            today_iso=TODAY,
        )

        self.assertIn("generated_by: CI-generated", out)
        self.assertNotIn("OpenAI", out)
        self.assertEqual(out.count("generated_by:"), 1)

    def test_missing_freshness_section_is_added(self):
        source = """---
domain: infra
last_reviewed: 2026-08-01
---

# Context
"""

        generated = source + "\nChanged\n"

        out = apply_deterministic_postprocessing(
            source_md=source,
            generated_md=generated,
            git_log="",
            today_iso=TODAY,
        )

        self.assertIn("## Freshness", out)
        self.assertIn(f"- `last_reviewed`: {TODAY}", out)
        self.assertIn("- `generated_by`: CI-generated", out)

    def test_template_style_bullets_are_updated_in_place(self):
        """`- **Last reviewed:**` is recognised, not shadowed by a second slug-style bullet.

        CONTEXT_TEMPLATE.md ships this style, so before it was recognised a template-shaped
        file grew a duplicate bullet on every run while the readable one stayed frozen.
        """
        source = """---
domain: infra
last_reviewed: 2026-08-01
---

# Context

## Freshness

- **Last reviewed:** 2026-08-01
- **Review confidence:** high
- **Generated by:** manual
- **Validated by:** Someone
"""

        generated = source + "\nChanged\n"

        out = apply_deterministic_postprocessing(
            source_md=source,
            generated_md=generated,
            git_log="",
            today_iso=TODAY,
        )

        self.assertIn(f"- **Last reviewed:** {TODAY}", out)
        self.assertIn("- **Generated by:** CI-generated", out)
        self.assertNotIn("`last_reviewed`", out)
        self.assertNotIn("`generated_by`", out)
        self.assertEqual(out.count("Last reviewed"), 1)
        self.assertEqual(out.count("Generated by"), 1)
        self.assertIn("- **Validated by:** Someone", out)

    def test_bullets_are_not_appended_below_the_recent_changes_block(self):
        """The recent-changes block bounds the Freshness section.

        It is the last thing in a template-shaped file, and the `## Freshness` heading regex
        would otherwise treat it as part of that section -- putting appended bullets under
        the git log.
        """
        source = """---
domain: infra
last_reviewed: 2026-08-01
---

# Context

## Freshness

- **Last reviewed:** 2026-08-01

Recent changes (last 7 days of git log):
old entry
"""

        generated = source.replace("# Context", "# Context\n\nA substantive change.")

        out = apply_deterministic_postprocessing(
            source_md=source,
            generated_md=generated,
            git_log="deadbee feat: something",
            today_iso=TODAY,
        )

        freshness = out.index("## Freshness")
        recent = out.index("Recent changes (last 7 days of git log):")

        self.assertLess(freshness, recent, "Freshness section must precede the log block")
        self.assertLess(
            out.index("Generated by"),
            recent,
            "an appended bullet must land among the bullets, not under the git log",
        )
        self.assertTrue(out.rstrip().endswith("deadbee feat: something"))

    def test_appended_bullet_follows_the_sections_existing_style(self):
        """A section written in one style does not end up carrying both."""
        prose_source = """---
domain: infra
---

## Freshness

- **Last reviewed:** 2026-08-01
"""
        slug_source = """---
domain: infra
---

## Freshness
- `last_reviewed`: 2026-08-01
"""

        for source, expected, unexpected in (
            (prose_source, "- **Generated by:** CI-generated", "`generated_by`"),
            (slug_source, "- `generated_by`: CI-generated", "**Generated by:**"),
        ):
            with self.subTest(source=expected):
                out = apply_deterministic_postprocessing(
                    source_md=source,
                    generated_md=source + "\nChanged\n",
                    git_log="",
                    today_iso=TODAY,
                )

                self.assertIn(expected, out)
                self.assertNotIn(unexpected, out)

    def test_recent_changes_section_is_added_when_absent(self):
        """A file with no log block gets one.

        It used to be conditional on the *source* already having the header, so a file
        generated from nothing never got one and never would -- which is every file
        repo getting its first context file, while the template said it was part of the shape.
        """
        source = """---
domain: infra
---

# Context

## Freshness

- **Last reviewed:** 2026-08-01
"""

        out = apply_deterministic_postprocessing(
            source_md=source,
            generated_md=source.replace("# Context", "# Context\n\nNew prose."),
            git_log="deadbee feat: something",
            today_iso=TODAY,
        )

        self.assertIn("Recent changes (last 7 days of git log):", out)
        self.assertTrue(out.rstrip().endswith("deadbee feat: something"))

    def test_a_log_only_change_does_not_bump_last_reviewed(self):
        """The 7-day window moves on its own; that is not a review."""
        source = """---
domain: infra
last_reviewed: 2026-08-01
---

# Context

## Freshness

- **Last reviewed:** 2026-08-01

Recent changes (last 7 days of git log):
last week's commits
"""

        out = apply_deterministic_postprocessing(
            source_md=source,
            generated_md=source,
            git_log="deadbee feat: brand new commit",
            today_iso=TODAY,
        )

        self.assertIn("deadbee feat: brand new commit", out)
        self.assertNotIn("last week's commits", out)
        self.assertIn("last_reviewed: 2026-08-01", out)
        self.assertIn("- **Last reviewed:** 2026-08-01", out)
        self.assertNotIn(TODAY, out)

    def test_git_log_is_rendered_as_a_markdown_list(self):
        """Raw `--oneline --stat` output renders as one run-together wall of text.

        Markdown collapses single newlines inside a paragraph, so every commit and stat line
        ran together. Commits become list items; git indents `--stat` lines, which is the
        signal to nest them under the commit they belong to.
        """
        git_log = (
            "d810a151 Merge pull request #1119\n"
            "7d97a205 Testing new context regenerator\n"
            " .github/workflows/regenerate-context.yaml | 2 +-\n"
            " 1 file changed, 1 insertion(+), 1 deletion(-)\n"
            "9f80cdd2 Merge pull request #1117"
        )

        out = apply_deterministic_postprocessing(
            source_md="# Context\n",
            generated_md="# Context\n\nChanged.\n",
            git_log=git_log,
            today_iso=TODAY,
        )

        self.assertIn("- d810a151 Merge pull request #1119", out)
        self.assertIn("  - .github/workflows/regenerate-context.yaml | 2 +-", out)
        self.assertIn("  - 1 file changed, 1 insertion(+), 1 deletion(-)", out)
        self.assertIn("- 9f80cdd2 Merge pull request #1117", out)

        # A blank line after the header, or the list is swallowed into the paragraph.
        self.assertIn("git log):\n\n- d810a151", out)

    def test_recent_changes_section_is_replaced_deterministically(self):
        source = """---
domain: infra
last_reviewed: 2026-08-01
---

# Context

Recent changes (last 7 days of git log):
old

## Freshness
- `last_reviewed`: 2026-08-01
"""

        generated = """---
domain: infra
last_reviewed: 2026-08-01
---

# Context

Recent changes (last 7 days of git log):
model text

## Freshness
- `last_reviewed`: 2026-08-01
"""

        out = apply_deterministic_postprocessing(
            source_md=source,
            generated_md=generated,
            git_log="abc123 Update docs",
            today_iso=TODAY,
        )

        self.assertIn("Recent changes (last 7 days of git log):\n\n- abc123 Update docs", out)

    def test_upsert_frontmatter_field_sets_repo_deterministically(self):
        md = """---
repo: UNSET
owner: Cinfra
---

# Context
"""

        out = upsert_frontmatter_field(md, "repo", "guidion-digital/code-infrastructure")

        self.assertIn("repo: guidion-digital/code-infrastructure", out)
        self.assertNotIn("repo: UNSET", out)

    def test_transform_is_idempotent(self):
        source = """---
domain: infra
last_reviewed: 2026-08-01
---

# Context

## Freshness
- `last_reviewed`: 2026-08-01
"""
        generated = source + "\nChanged\n"

        once = apply_deterministic_postprocessing(
            source_md=source,
            generated_md=generated,
            git_log="",
            today_iso=TODAY,
        )
        twice = apply_deterministic_postprocessing(
            source_md=once,
            generated_md=once,
            git_log="",
            today_iso=TODAY,
        )

        self.assertEqual(once, twice)


if __name__ == "__main__":
    unittest.main()
